# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impeachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='register_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
